<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container51czs90\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container51czs90/appProdProjectContainer.php') {
    touch(__DIR__.'/Container51czs90.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container51czs90\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container51czs90\appProdProjectContainer([
    'container.build_hash' => '51czs90',
    'container.build_id' => '8edd25e2',
    'container.build_time' => 1557905144,
], __DIR__.\DIRECTORY_SEPARATOR.'Container51czs90');
